/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class defaultPackage_JavaToC */

#ifndef _Included_defaultPackage_JavaToC
#define _Included_defaultPackage_JavaToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     defaultPackage_JavaToC
 * Method:    calcDiffraction
 * Signature: ([LdefaultPackage/JAtom;[LdefaultPackage/JPixel;[I)[LdefaultPackage/JPixel;
 */
JNIEXPORT jobjectArray JNICALL Java_defaultPackage_JavaToC_calcDiffraction
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jintArray);

/*
 * Class:     defaultPackage_JavaToC
 * Method:    cuInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_defaultPackage_JavaToC_cuInit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
